name: Test Suite
on: push
jobs:
  test:
    runs-on: buildjet-32vcpu-ubuntu-2204
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: tes
        run: docker run ricardmodi/peli:latest
