name: Test Suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: addnab/docker-run-action@v3
      with:
        image: docker:latest
        shell: bash
        run: |
          echo "first line"
          echo "second line"
          ./opt/alahsui/entrypoint
